name = "alertapostas-fresh"
main = "src/index.js"
compatibility_date = "2025-09-17"
compatibility_flags = ["nodejs_compat"]

# Configurações de cron triggers (para workers automáticos)
[triggers]
crons = [
  "*/5 * * * *",  # A cada 5 minutos - trigger workers
  "*/1 * * * *"   # A cada 1 minuto - atualizar dados do site
]

# Migração para resolver Durable Objects
[[migrations]]
tag = "v1"
deleted_classes = ["BotState"]
