name = "alertapostas-secure"
main = "src/index-secure.js"
compatibility_date = "2025-09-17"
compatibility_flags = ["nodejs_compat"]

# Variáveis de ambiente
[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://alertapostas-backend.ecarvalho140.workers.dev"
API_FOOTBALL_KEY = "623ead667fb69f339d1e8f9a366de721"
TELEGRAM_TOKEN = "8031960776:AAFmB-UhPTfj3YauD6PPkjQW2VTsngJ3AIU"
TELEGRAM_GROUP_ID = "-1002937302746"
