global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Alert@Postas Backend
  - job_name: 'alertpostas-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Alert@Postas ML Modules
  - job_name: 'alertpostas-ml'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/ml/metrics'
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # MLflow
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']

  # Node Exporter (sistema)
  - job_name: 'node'
    static_configs:
      - targets: ['backend:9100', 'frontend:9100']
